site:
  title: "Daily AI Papers"
  description: "Latest papers in AI research - RAG, Knowledge Graph, and more"
  url: "https://ysj1173886760.github.io/daily-papers-site"
  author: "AI Research Team"
  email: "ysj1173886760@gmail.com"
  github_repo: "https://github.com/ysj1173886760/daily-papers-site"
  main_project: "https://github.com/ysj1173886760/daily-paper-v2"

# RSS设置
rss:
  max_items: 50
  language: "zh-cn"

# 网站特性
features:
  - responsive_design
  - rss_feed
  - syntax_highlighting
  - mobile_friendly